[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vs"
version = "0.0.2"
requires-python = "~= 3.9"
dependencies = [
    "requests",
    "iterfzf"
]

[project.scripts]
vs = "vs.main:main"

[tool.poe.tasks]
run = "vs"
